services:

  mysql:
    container_name: "mysql"
    hostname: "mysql"
    image: yobasystems/alpine-mariadb:latest
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sql_blog_audit
      MYSQL_DATABASE: sql_blog_audit
      MYSQL_USER: sql_blog_audit
      MYSQL_PASSWORD: sql_blog_audit
    volumes:
      - ./sql/employee_audit.sql:/tmp/employee_audit.sql
